CREATE TABLE BOWLER_GAME(
   ID             INT     PRIMARY KEY     NOT NULL,
   F_BOWLER       INT     REFERENCES BOWLER(ID)    NOT NULL,
   THROW1         INT,
   THROW2         INT,
   THROW3         INT,
   THROW4         INT,
   THROW5         INT,
   THROW6         INT,
   THROW7         INT,
   THROW8         INT,
   THROW9         INT,
   THROW10         INT,
   THROW11         INT,
   THROW12         INT,
   THROW13         INT,
   THROW14         INT,
   THROW15         INT,
   THROW16         INT,
   THROW17         INT,
   THROW18         INT,
   THROW1ç         INT,
   THROW19         INT,
   THROW20         INT,
   THROW21         INT,
   TOTAL           INT
);